// Generated by https://quicktype.io

export interface Champion {
  id: number;
  key: string;
  name: string;
  image_url: string;
  evolve: Evolve[];
  enemy_tips: string[];
  ally_tips: string[];
  skins: Skin[];
  passive: Passive;
  spells: Spell[];
}

export interface Evolve {
  key: string;
  name: string;
  image_url: string;
}

export interface Passive {
  name: string;
  description: string;
  image_url: string;
  video_url: string;
}

export interface Skin {
  id: number;
  name: string;
  has_chromas: boolean;
  splash_image: string;
  loading_image: string;
  tiles_image: string;
  centered_image: string;
  skin_video_url: null;
  prices: Price[] | null;
  sales: Sale[] | null;
}

export interface Price {
  currency: Currency;
  cost: number;
}

export enum Currency {
  IP = 'IP',
  Rp = 'RP',
}

export interface Sale {
  currency: Currency;
  cost: number;
  discount_rate: number;
  started_at: Date;
  ended_at: Date;
}

export interface Spell {
  key: Key;
  name: string;
  description: string;
  max_rank: number;
  range_burn: number[];
  cooldown_burn: number[];
  cost_burn: number[];
  tooltip: string;
  image_url: string;
  video_url: string;
}

export enum Key {
  E = 'E',
  Q = 'Q',
  R = 'R',
  W = 'W',
}
