// Generated by https://quicktype.io

export interface Profile {
  id: number;
  summoner_id: string;
  acct_id: string;
  puuid: string;
  name: string;
  internal_name: string;
  profile_image_url: string;
  level: number;
  updated_at: Date;
  renewable_at: Date;
  team_info: null;
  lp_histories: LpHistory[];
  previous_seasons: PreviousSeason[];
  league_stats: LeagueStat[];
  most_champions: MostChampions;
  recent_champion_stats: RecentChampionStat[];
  ladder_rank: LadderRank;
  recent_soloranked_analysis: RecentSolorankedAnalysis[];
  recent_normal_analysis: unknown[];
  championsById: { [key: string]: ChampionsByID };
  seasonsById: { [key: string]: Season };
  seasons: Season[];
  tiersImageData: TiersImageDatum[];
}

export interface ChampionsByID {
  id: number;
  key: string;
  name: string;
  image_url: string;
  evolve: Evolve[];
  enemy_tips: string[];
  ally_tips: string[];
  skins: Skin[];
  passive: Passive;
  spells: Spell[];
}

export interface Evolve {
  key: string;
  name: string;
  image_url: string;
}

export interface Passive {
  name: string;
  description: string;
  image_url: string;
  video_url: string;
}

export interface Skin {
  id: number;
  name: string;
  has_chromas: boolean;
  splash_image: string;
  loading_image: string;
  tiles_image: string;
  centered_image: string;
  skin_video_url: null;
  prices: Price[] | null;
  sales: Sale[] | null;
}

export interface Price {
  currency: Currency;
  cost: number;
}

export enum Currency {
  IP = 'IP',
  Rp = 'RP',
}

export interface Sale {
  currency: Currency;
  cost: number;
  discount_rate: number;
  started_at: Date;
  ended_at: Date;
}

export interface Spell {
  key: Key;
  name: string;
  description: string;
  max_rank: number;
  range_burn: number[];
  cooldown_burn: number[];
  cost_burn: number[];
  tooltip: string;
  image_url: string;
  video_url: string;
}

export enum Key {
  E = 'E',
  Q = 'Q',
  R = 'R',
  W = 'W',
}

export interface LadderRank {
  rank: number;
  total: number;
}

export interface LeagueStat {
  queue_info: QueueInfo;
  tier_info: TierInfo;
  win: number | null;
  lose: number | null;
  is_hot_streak: boolean;
  is_fresh_blood: boolean;
  is_veteran: boolean;
  is_inactive: boolean;
  series: Series | null;
  updated_at: Date | null;
  league?: League;
}

export interface League {
  id: number;
  name: string;
  udid: string;
  translate: string;
}

export interface QueueInfo {
  id: number;
  queue_translate: string;
  game_type: string;
}

export interface TierInfo {
  tier: null | string;
  division: number | null;
  lp: number | null;
  tier_image_url: string;
  border_image_url: null | string;
}

export interface LpHistory {
  created_at: Date;
  tier_info: TierInfo;
  elo_point: number;
}

export interface MostChampions {
  game_type: string;
  season_id: number;
  play: number;
  win: number;
  lose: number;
  champion_stats: { [key: string]: number }[];
}

export interface PreviousSeason {
  season_id: number;
  tier_info: TierInfo;
  created_at: Date;
}

export interface RecentChampionStat {
  id: number;
  play: number;
  win: number;
  kill: number;
  death: number;
  assist: number;
}

export interface RecentSolorankedAnalysis {
  key: string;
  value: number;
  avgInTier: number;
  percentInTop: number;
}

export interface Season {
  id: number;
  value: number;
  display_value: number;
  is_preseason: boolean;
}

export interface TiersImageDatum {
  name: string;
  tier_image_url: string;
  border_image_url: string;
  tier_mini_image_url: string;
}

export interface Series {
  target: number;
  win:    number;
  lose:   number;
}

