// Generated by https://quicktype.io

export interface OptionKey {
  name: string;
  text: string;
  defaultValue: boolean;
}

export const OptionKeys: {
  [key: string]: OptionKey;
} = {
  OPTION_KEY_UPGRADE_NOTIFICATION: {
    name: 'OPTION_KEY_UPGRADE_NOTIFICATION',
    text: '擴充套件更新通知',
    defaultValue: true,
  },
  OPTION_KEY_LIVE_NOTIFICATION: {
    name: 'OPTION_KEY_LIVE_NOTIFICATION',
    text: '開台通知',
    defaultValue: true,
  },
  OPTION_KEY_CHAT_MESSAGE: {
    name: 'OPTION_KEY_CHAT_MESSAGE',
    text: '顯示聊天室訊息',
    defaultValue: true,
  },
};
